compiler-rt: Use mmap.PAGESIZE instead of os.sysconf(SC_PAGESIZE).
os.sysconf seems not to be available in Windows:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'sysconf'